EXP_NAME: "basic_32"

TRAIN:
    LEARNING_RATE: 0.01
    IMAGE_SIZE: 32
    DATA_DIR: '~/workspace/ton_618/data/cifar10'
    BATCH_SIZE: 128
    NUM_CLASSES: 10
    NUM_EPOCHS: 20

PRINT_FREQUENCY: 100

TEST:
    DATA_DIR: '~/workspace/ton_618/data/cifar10'
