EXP_NAME: "basic_cifar_32"
DEVICE: "gpu"
TRAIN:
    LEARNING_RATE: 0.01
    IMAGE_SIZE: 224 # resized from 32
    DATASET: "cifar"
    DATA_DIR: 'data/cifar10'
    BATCH_SIZE: 128
    NUM_CLASSES: 10
    NUM_EPOCHS: 20

PRINT_FREQUENCY: 100

TEST:
    DATASET: "cifar"
    DATA_DIR: 'data/cifar10'
